"use client";
import { useEffect, useState, FormEvent } from 'react';
import { MetricCard } from '@/components/admin/MetricCard';
import { api, errorMessage } from '@/lib/api';
import type { AdminStats, VisitAnalytics } from '@/types';
const initial={from:new Date(Date.now()-29*86400000).toISOString().slice(0,10),to:new Date().toISOString().slice(0,10)};
export default function AdminOverview(){
  const [range,setRange]=useState(initial);const [query,setQuery]=useState(initial);
  const [stats,setStats]=useState<AdminStats|null>(null);const [visits,setVisits]=useState<VisitAnalytics|null>(null);
  const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  useEffect(()=>{let active=true;Promise.all([api.getStats(),api.getAnalytics(query.from,query.to)]).then(([stats,visits])=>{if(active){setStats(stats);setVisits(visits);setError('');}}).catch(e=>{if(active)setError(errorMessage(e));}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[query]);
  const apply=(e:FormEvent)=>{e.preventDefault();setLoading(true);setQuery({...range});};
  const maxViews=Math.max(1,...(visits?.daily.map(day=>day.pageViews)||[]));
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Website Analytics</h1><p className="text-sm text-gray-500">Site traffic and foundation activity. Visitor counts are estimates based on anonymous browser identifiers.</p></div>
    <form onSubmit={apply} className="flex flex-wrap gap-3 items-end"><label className="text-sm">From<input type="date" required value={range.from} max={range.to} onChange={e=>setRange({...range,from:e.target.value})} className="block border rounded-xl p-2 bg-white"/></label><label className="text-sm">To<input type="date" required value={range.to} min={range.from} max={initial.to} onChange={e=>setRange({...range,to:e.target.value})} className="block border rounded-xl p-2 bg-white"/></label><button disabled={loading} className="bg-[#2C5F2D] text-white px-4 py-2 rounded-xl">{loading?'Loading...':'Apply dates'}</button></form>
    {error&&<p role="alert" className="text-red-700">{error}</p>}
    {visits&&<><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><MetricCard title="Page Views" value={visits.pageViews} sub="Pages viewed" icon="◧"/><MetricCard title="Visits" value={visits.visits} sub="Sessions, with a 30-minute inactivity limit" icon="◐"/><MetricCard title="Unique Visitors" value={visits.uniqueVisitors} sub="Estimated browsers in this period" icon="☷"/></div>
      <section className="bg-white rounded-2xl border p-5"><h2 className="font-semibold">Daily Page Views</h2><p className="text-xs text-gray-500 mt-1">{visits.from} to {visits.to} (UTC)</p><div className="flex items-end gap-1 h-44 mt-5" role="img" aria-label={`Daily page views from ${visits.from} to ${visits.to}`}>{visits.daily.map(day=><div key={day.date} title={`${day.date}: ${day.pageViews} views, ${day.visits} visits`} className="flex-1 bg-[#97BC62] rounded-t min-w-0" style={{height:`${day.pageViews?Math.max(3,day.pageViews/maxViews*100):1}%`}}/>)}</div><div className="flex justify-between text-xs text-gray-500 mt-2"><span>{visits.from}</span><span>{visits.to}</span></div><details className="mt-4 text-sm"><summary className="cursor-pointer">View daily numbers</summary><table className="w-full mt-2"><thead><tr><th className="text-left">Date</th><th>Views</th><th>Visits</th><th>Visitors</th></tr></thead><tbody>{visits.daily.map(day=><tr key={day.date}><td>{day.date}</td><td className="text-center">{day.pageViews}</td><td className="text-center">{day.visits}</td><td className="text-center">{day.uniqueVisitors}</td></tr>)}</tbody></table></details></section>
      <div className="grid md:grid-cols-2 gap-4"><section className="bg-white rounded-2xl border p-5"><h2 className="font-semibold mb-3">Popular Pages</h2>{visits.topPages.map(page=><div key={page.path} className="flex justify-between gap-4 border-t py-2 text-sm"><span className="break-all">{page.path}</span><span>{page.views}</span></div>)}{!visits.topPages.length&&<p className="text-sm text-gray-500">No visits recorded in this period.</p>}</section><section className="bg-white rounded-2xl border p-5"><h2 className="font-semibold mb-3">Referring Sites</h2>{visits.referrers.map(source=><div key={source.source} className="flex justify-between border-t py-2 text-sm"><span>{source.source}</span><span>{source.views}</span></div>)}</section></div>
      {visits.truncated&&<p role="status">This period reached the 50,000-page-view reporting limit. Select a shorter period for complete results.</p>}
    </>}
    {stats&&<section className="bg-white rounded-2xl border p-5 space-y-3"><h2 className="font-semibold">Foundation Activity (All Time)</h2><div className="grid sm:grid-cols-3 gap-4">{stats.permissions.includes('pledges.view')&&<div><p className="text-sm text-gray-500">Donation pledges: {stats.totalDonations}</p>{Object.entries(stats.totalsByCurrency).map(([currency,total])=><p key={currency} className="font-semibold">{currency} {total.toLocaleString()}</p>)}</div>}{stats.permissions.includes('events.view')&&<p>Upcoming events: {stats.upcomingEvents}</p>}{stats.permissions.includes('contacts.view')&&<p>Contact inquiries: {stats.totalContacts}</p>}</div></section>}
    <p className="text-xs text-gray-500">Tracking starts when this version is used; past visits cannot be recovered. Admin pages and browsers opting out of tracking are excluded. No IP addresses or query strings are stored.</p>
  </div>;
}
